apiVersion: v1
kind: Secret
metadata:
  name: subscription-control-api-token
  namespace: subscription-control
type: Opaque
stringData:
  API_TOKEN: iPaVaOP-yoRm9x0vXTIzOSnTht_OWmTcLiPTgdCJIZGEShQo7Ao642sIHzWIVkTG
