apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: subscription-control
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: redhat123
  MYSQL_USER: subscription
  MYSQL_PASSWORD: redhat123
