apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscription-control-sa
  namespace: subscription-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscription-control-cr
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["project.openshift.io"]
    resources:
      - projects
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources:
      - managedclusters
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: subscription-control-crb
subjects:
  - kind: ServiceAccount
    name: subscription-control-sa
    namespace: subscription-control
roleRef:
  kind: ClusterRole
  name: subscription-control-cr
  apiGroup: rbac.authorization.k8s.io
