apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: subscription-control
type: Opaque
stringData:
  POSTGRESQL_ADMIN_PASSWORD: redhat123
  POSTGRESQL_USER: subscription
  POSTGRESQL_PASSWORD: redhat123
